apiVersion: v1
kind: Service
metadata:
  name: math-svc
  namespace: math
spec:
  selector:
    app: math-svc
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
